apply plugin: 'com.android.library'

android {
    namespace 'dev.mpgd.capacitor.playbilling'
    compileSdk project.hasProperty('compileSdkVersion') ? rootProject.ext.compileSdkVersion : 36

    defaultConfig {
        minSdkVersion project.hasProperty('minSdkVersion') ? rootProject.ext.minSdkVersion : 24
        targetSdkVersion project.hasProperty('targetSdkVersion') ? rootProject.ext.targetSdkVersion : 36
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation project(':capacitor-android')
    implementation 'com.android.billingclient:billing:9.1.0'
    compileOnly 'androidx.appcompat:appcompat:1.7.1'
}
